# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0035_auto_20180223_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutdata',
            name='autonCube',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='autonLine',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='autonSwitch',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='canClimb',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='cubesExchange',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='cubesScale',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='cubesSwitch',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='matchNumber',
        ),
    ]
