# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0042_auto_20180225_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityblock',
            options={'verbose_name': 'Community Block', 'verbose_name_plural': 'Community Blocks'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='historyblock',
            options={'verbose_name': 'History Block', 'verbose_name_plural': 'History Blocks'},
        ),
        migrations.AlterModelOptions(
            name='matchdata',
            options={'verbose_name': 'Match Data', 'verbose_name_plural': 'Match Data'},
        ),
        migrations.AlterModelOptions(
            name='membermodel',
            options={'ordering': ['last', 'student'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='scoutdata',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='sponsormodel',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='staffmodel',
            options={'ordering': ['last', 'staff'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='matchdata',
            name='matchWon',
            field=models.BooleanField(default=False),
        ),
    ]
