# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoLine', models.BooleanField(default=False)),
                ('cubesSwitch', models.IntegerField(blank=True, default=0)),
                ('cubesExchange', models.IntegerField(blank=True, default=0)),
                ('cubesScale', models.IntegerField(blank=True, default=0)),
                ('canClimb', models.BooleanField(default=False)),
                ('refNumber', models.IntegerField(default=1)),
                ('timeCube', models.FloatField(default=0)),
                ('timeClimb', models.FloatField(default=0)),
                ('timeSwitch', models.FloatField(default=0)),
                ('timeScale', models.FloatField(default=0)),
                ('matchWon', models.BooleanField(default=False)),
                ('autoScale', models.BooleanField(default=False)),
                ('autoSwitch', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Match Data',
                'verbose_name_plural': 'Match Data',
            },
        ),
        migrations.CreateModel(
            name='ScoutData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('script', models.CharField(db_index=True, max_length=100, unique=True)),
                ('autoLine', models.BooleanField(default=False)),
                ('autoScale', models.BooleanField(default=False)),
                ('autoSwitch', models.BooleanField(default=False)),
                ('climb', models.BooleanField(default=False)),
                ('scale', models.BooleanField(default=False)),
                ('switch', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scouting.EventModel')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='matchdata',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='scouting.ScoutData'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='scouting.YearModel'),
        ),
    ]
