# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0005_remove_matchdata_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='year',
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scouting.EventModel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='YearModel',
        ),
    ]
