# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0007_auto_20190218_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='cubesExchange',
            new_name='cargoPlaced',
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='cubesScale',
            new_name='habLevelStart',
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='autoLine',
            new_name='habLine',
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='cubesSwitch',
            new_name='hatchesPlaced',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='autoScale',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='autoSwitch',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='canClimb',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='refNumber',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='timeClimb',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='timeCube',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='timeScale',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='timeSwitch',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='autoLine',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='autoScale',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='autoSwitch',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='climb',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='switch',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='habLevelEnd',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='sandStormCargoAttempts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='sandStormCargoSuccesses',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
