# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0033_auto_20180223_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoLine', models.BooleanField(default=False)),
                ('cubesSwitch', models.IntegerField(blank=True, default=0)),
                ('cubesExchange', models.IntegerField(blank=True, default=0)),
                ('cubesScale', models.IntegerField(blank=True, default=0)),
                ('canClimb', models.BooleanField(default=False)),
                ('refNumber', models.IntegerField(default=1)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sponsors.ScoutData')),
            ],
        ),
    ]
