# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_eventmodel_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='script',
            new_name='slug',
        ),
    ]
