# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0004_auto_20181008_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='event',
        ),
    ]
