# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0017_auto_20171121_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='url',
            field=models.URLField(default='https://docs.djangoproject.com/en/1.11/ref/models/fields/#urlfield'),
            preserve_default=False,
        ),
    ]
