# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0024_auto_20180216_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdata',
            name='cubesExchange',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='cubesScale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='cubesSwitch',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='matchNmber',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
