# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0046_auto_20180926_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='place',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
