# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0006_auto_20190216_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='matchdata',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='event',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scouting.EventModel'),
            preserve_default=False,
        ),
    ]
