# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-17 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20171017_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormodel',
            name='sponsorclass',
            field=models.CharField(default='hello', max_length=10),
            preserve_default=False,
        ),
    ]
