# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_sponsormodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='sponsor_image'),
        ),
    ]
