# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0026_auto_20180219_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdata',
            name='slug',
            field=models.CharField(db_index=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
