# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0038_matchdata_timeswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='timeScale',
            field=models.FloatField(default=0),
        ),
    ]
