# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-22 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0019_auto_20171122_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='sponsor_image')),
                ('place', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Headers',
            new_name='Header',
        ),
        migrations.DeleteModel(
            name='HomeModel',
        ),
    ]
