# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-22 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0020_auto_20171122_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='CommunityBlock',
        ),
    ]
