# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0028_auto_20180220_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutdata',
            name='script',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
