# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0031_remove_scoutdata_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdata',
            name='script',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
