# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0032_scoutdata_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdata',
            name='autonSwitch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoutdata',
            name='script',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
