# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0045_auto_20180407_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='year',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='team',
        ),
        migrations.RemoveField(
            model_name='scoutdata',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
        migrations.DeleteModel(
            name='MatchData',
        ),
        migrations.DeleteModel(
            name='ScoutData',
        ),
        migrations.DeleteModel(
            name='YearModel',
        ),
    ]
