# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0012_auto_20171115_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermodel',
            options={'ordering': ['student', 'last']},
        ),
    ]
