# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_auto_20171121_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermodel',
            options={'ordering': ['last', 'student']},
        ),
    ]
