# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0023_scoutdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdata',
            name='autonCube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='autonLine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='canClimb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
