# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-19 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_sponsormodel_sponsorclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('shortcode', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.RemoveField(
            model_name='sponsormodel',
            name='sponsorclass',
        ),
        migrations.AddField(
            model_name='sponsormodel',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='sponsors.SponsorClassModel'),
            preserve_default=False,
        ),
    ]
