# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20171121_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
