# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_auto_20171113_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormodel',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='sponsors.SponsorClassModel'),
            preserve_default=False,
        ),
    ]
