# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-15 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0010_auto_20171114_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
