# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0036_auto_20180224_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='timeClimb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='timeCube',
            field=models.FloatField(default=0),
        ),
    ]
