# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_membermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsormodel',
            name='category',
        ),
        migrations.AddField(
            model_name='sponsormodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
