# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0016_headers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headers',
            old_name='Body',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='headers',
            name='button',
            field=models.CharField(max_length=20),
        ),
    ]
