# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0007_sponsormodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('update', models.TextField(blank=True)),
                ('whatis', models.TextField(blank=True)),
            ],
        ),
    ]
