# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-14 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0009_auto_20171114_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='last',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='last',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
