# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0015_auto_20171121_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('button', models.CharField(max_length=10)),
                ('Body', models.TextField(blank=True)),
            ],
        ),
    ]
