# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0040_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutdata',
            name='autoLine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='autoSwitch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='autoSxcale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='scale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutdata',
            name='switch',
            field=models.BooleanField(default=False),
        ),
    ]
