# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0043_auto_20180226_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='autoScale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='autoSwitch',
            field=models.BooleanField(default=False),
        ),
    ]
